using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameControl : MonoBehaviour

{
    public static GameControl instance;
    public GameObject gameOverText;
    public bool gameOver = false;

    void awake()
    {
        if (instance == null)
        {
            instance = this;
        }
        else if (instance != this)
        {
             Destroy (gameObject); 
        }
    }
        void Update()
        {
        }
        public void BirdDied()
        {
            gameOverText.SetActive(true);
            gameOver = true;
        }
    
}
